name: pr_check

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        profile: minimal
    - name: Install trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install Node.js Dependencies
      run: npm ci
    - name: Build Frontend
      run: trunk build
    - name: Build Backend
      run: cargo build --features hydration
    - name: Run tests
      run: cargo test --verbose
